# Generated by Django 2.2.7 on 2019-11-28 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='time_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='login_user',
            name='time_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Hints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint', models.CharField(max_length=500)),
                ('time_stamp', models.DateTimeField(auto_now=True)),
                ('linked_to_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Category')),
                ('linked_to_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Question')),
            ],
        ),
    ]
