# Generated by Django 2.2.7 on 2019-11-28 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20191128_0651'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hints',
        ),
    ]
