# Generated by Django 2.2.7 on 2019-11-28 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_hint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hint',
            name='linked_to_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Category'),
        ),
        migrations.AlterField(
            model_name='hint',
            name='linked_to_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Question'),
        ),
    ]
