# Generated by Django 2.2.7 on 2019-12-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20191128_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_user',
            name='role',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
