# Generated by Django 2.2.7 on 2019-12-13 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20191203_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_user',
            name='email_query_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='login_user',
            name='email_verification_check',
            field=models.BooleanField(default=False),
        ),
    ]
