# Generated by Django 2.2.7 on 2019-12-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20191217_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_user',
            name='continue_with_email',
            field=models.BooleanField(default=False),
        ),
    ]
