# Generated by Django 2.2.7 on 2019-12-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
