# Generated by Django 2.2.7 on 2019-12-26 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_auto_20191226_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='folder',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.Folder'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='settbl',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.SetTable'),
            preserve_default=False,
        ),
    ]
