# Generated by Django 2.2.7 on 2019-12-27 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_auto_20191226_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('hint', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Category')),
            ],
        ),
        migrations.RemoveField(
            model_name='hint',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='hint',
            name='linked_to_category',
        ),
        migrations.RemoveField(
            model_name='hint',
            name='linked_to_question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='creator',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Hint',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
