# Generated by Django 2.2.7 on 2019-12-27 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_auto_20191227_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardcontent',
            old_name='category_id',
            new_name='category',
        ),
    ]
