# Generated by Django 2.2.7 on 2020-01-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_auto_20191227_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardcontent',
            name='file_path',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
