# Generated by Django 2.2.7 on 2020-01-09 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_auto_20200109_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uservoiceinput',
            name='creator',
        ),
    ]
