# Generated by Django 2.2.7 on 2020-01-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_remove_uservoiceinput_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardcontent',
            old_name='file_path',
            new_name='answer_file_path',
        ),
        migrations.AddField(
            model_name='cardcontent',
            name='question_file_path',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
