# Generated by Django 2.2.7 on 2020-01-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_auto_20200115_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardcontent',
            name='hint_file_path',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cardcontent',
            name='answer_file_path',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cardcontent',
            name='question_file_path',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
