# Generated by Django 2.2.7 on 2020-12-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_reportresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='recent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
